version: '3.8'

services:
  flask-app:
    image: python:3.9
    container_name: peaceful-joi
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: "python app.py"
