version: "3.8"

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/python-docker
    command: python app.py
