version: 3.10.7

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: demojenkisv2
    container_name: Peaceful-jones
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/python-docker
    command: python app.py
