version: '3'

services:

  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp
    container_name: webapp
    ports:
     - "5000:5000"
    environment:
     - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
