version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demojenkinsv2
    container_name: app
    restart: always
    ports:
      - "5000:5000" 
    volumes:
      - .:/app
    command: python app.py
